### ISSUE TITLE
BUG: download_fastq report error

### ISSUE THREAD

**Issue by bioinfolabmu** [vanheeringen-lab/seq2science#1016]
**Describe the bug**
I saw your publication yesterday and now I am trying your tool now. I met the first error with the work flow of download-fastq

**To Reproduce**
(1) My "samples.tsv" is very simple, and only contains the following lines:

# for help with filling out the samples.tsv:
# https://vanheeringen-lab.github.io/seq2science/content/workflows/download_fastq.html#filling-out-the-samples-tsv
# also make sure that you use tab as a delimiter
sample
SRR8984523

(2) My "config.yaml" has the following lines:

# tab-separated file
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
# fastq_dir: (default is inside result_dir) # where to download the fastqs

fqsuffix: fastq
fqext1: R1
fqext2: R2

(3)  This is the command that I run the workflow

seq2science run download-fastq  --cores 4

**Expected behavior**
During the process of executing this workflow, I checked that there was a file being generated in the result folder and then size kept growing.  At the end of the procedure,  the file was automatically deleted and error was reported. 
 
**Screenshots**
If applicable, add screenshots to help explain your problem.  I have attached the log file as the attachment 
[seq2science.2023-11-16T223515.101184.log](https://github.com/vanheeringen-lab/seq2science/files/13390909/seq2science.2023-11-16T223515.101184.log)

**Comment by bioinfolabmu** [comment]
I tried the workflow one more time by adding one file to download, with --cores 2 Here is the snap shot. 
![Screenshot from 2023-11-17 07-48-23](https://github.com/vanheeringen-lab/seq2science/assets/12627448/9b57bc81-5076-4717-b0d8-64a46dc8bcc3)
As you can see, the downloading files were 1 G in size and then, they were all gone with the  same message as reported in my previous message.

**Comment by Maarten-vd-Sande** [comment]
Thanks for your interest in seq2science. Not sure what the problem is... I just checked and the download works for me, and thus it should work for you too!!

- I noticed the download takes around 45 minutes for your rule to crash. But the file is about 2GB. Where are you located? Perhaps the European ENA servers are too far? 
- When a rule fails, it outputs to a file. Can you show the content of the log file? It is located at: /home/mubil/Downloads/Seq2science/proj_download/results/log/ena2fastq_SE/SRR8984523.log

**Comment by bioinfolabmu** [comment]
Alright. I figured this out. It is not a bug.  The problem is because that my disk is full. I have no problem downloading the data . 
Thank you very much for your quick response.

**Comment by Maarten-vd-Sande** [comment]
Great you worked it out! :)

On 18 Nov 2023, at 00:35, bioinfolabmu ***@***.***> wrote:

﻿

Alright. I figured this out. It is not a bug. The problem is because that my disk is full. I have no problem downloading the data .
Thank you very much for your quick response.
