### ISSUE TITLE
FR: remove common variants

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#271]
In the human genome there are common variants which people want to have removed 9/10 times before alingment, me too.

**Comment by Maarten-vd-Sande** [comment]
https://github.com/lh3/bwa/blob/master/README-alt.md

**Comment by Maarten-vd-Sande** [comment]
@siebrenf so is this now "fixed"? Should we add some docs about this?

**Comment by siebrenf** [comment]
genomepy will download the primary assembly from Ensembl by default. I havent encountered the choice for toplevel assemblies on UCSC or NCBI, so for fresh genomes: yes. 

But seq2science does not check if the local genome is the primary assembly. Not sure how to check for this: the size of the genome, the presence of "toplevel" in the genome name?

**Comment by siebrenf** [comment]
the linked PR removes regions marked with "alt". There might still be similar variants(?)
