### ISSUE TITLE
FR: Improve docs

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#277]
Lots of changes have been added and lots are in develop. We should make sure the docs are up to date.

**Comment by siebrenf** [comment]
I've been working on that yesterday. should be fixed today xD

**Comment by siebrenf** [comment]
replicate handling is workflow agnostic, similar to trackhubs. 

I was originally planning on making it a numberless page, and referencing to it on every workflow page, similar to how I did with the Trackhub page. 

Would you agree to this method, or is that too messy?

**Comment by Maarten-vd-Sande** [comment]
Personally I don't like numberless pages since you can not order them, that's why I added the nrs. We definitely should reference this in the other workflows indeed

**Comment by JGASmits** [comment]
I can write the scATAC docs page! Should I just update the README.md in the scATAC branch?

**Comment by Maarten-vd-Sande** [comment]
Yes and no, this is the location for the main docs:
https://github.com/vanheeringen-lab/snakemake-workflows/wiki/8.-scATAC-seq

**Comment by JGASmits** [comment]
Alright, ill put it on my "to do" list :)

**Comment by Maarten-vd-Sande** [comment]
@Maarten-vd-Sande: add docs for control/input. Seems to be missing

**Comment by Maarten-vd-Sande** [comment]
@Maarten-vd-Sande also add documentation where each output can be found.

**Comment by Maarten-vd-Sande** [comment]
@Maarten-vd-Sande improve trackhub docs. (e.g. reads are deduplicated)

**Comment by Maarten-vd-Sande** [comment]
@Maarten-vd-Sande Add docs for LC_COLLATE stuff..

**Comment by Maarten-vd-Sande** [comment]
@siebrenf @JGASmits are we happy with the current wiki structure? Or should we move to a more "real" docs?

**Comment by Maarten-vd-Sande** [comment]
@siebrenf @JGASmits when making changes to the docs please also make them in the docs branch, otherwise those changes will be lost.

https://github.com/vanheeringen-lab/snakemake-workflows/pull/337

**Comment by Maarten-vd-Sande** [comment]
@JGASmits: I leave the scATAC docs in your responsibility
@siebrenf: For you RNA-seq

I think there is no real way to avoid duplicate docs without doing something complicated, so I decided to just ignore that. It's also a better user-experience. I think the current layout is fine for the workflow docs. Do you agree? If so, please finish "your" docs in the same layout there is now for the others.

**Comment by JGASmits** [comment]
So we can just work in the .md files in the seq2science/docs/content/workflows/? 
Or is there still a specific branch to work in?

**Comment by Maarten-vd-Sande** [comment]
I started a docs branch: https://github.com/vanheeringen-lab/seq2science/tree/docs

Best to work in here. It will update the website when you make changes, so you can see if it looks okay.
