### ISSUE TITLE
FR: Check samples.tsv with PandasSchema

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#328]
**Is your feature request related to a problem? Please describe.**
See https://github.com/TMiguelT/PandasSchema. Never used it before, but the example seems really nice! Would be much easier to debug a faulty samples.tsv.

**Comment by siebrenf** [comment]
I wanted to simplify how we handle the samples.tsv, especially around replicates and conditions, to reduce the amount of code and checks a bit. I could take this along

**Comment by siebrenf** [comment]
Some options, such as optional columns, are not yet supported. I'll check back again later :)
