### ISSUE TITLE
FR: Support rerunning

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#342]
Maybe this should even be the default behaviour?
https://snakemake.readthedocs.io/en/stable/project_info/faq.html#snakemake-does-not-trigger-re-runs-if-i-add-additional-input-files-what-can-i-do

**Comment by Maarten-vd-Sande** [comment]
Perhaps in combination with  `--list-params-changes`! 

This way we can delete all the files that come out of `--list-params-changes` and `--list-input-changes`!!

**Comment by Maarten-vd-Sande** [comment]
I'M WORKING ON IT :angry:

**Comment by siebrenf** [comment]
It's WIP stalebot. Shoo
