### ISSUE TITLE
BUG: Edge-case: starting with downstream file

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#347]
**Describe the bug**
starting a workflow without fastqs, but with downstream files still causes the `FileLock(layout_cachefile_lock)` to complain.
Adding the fastq files and rerunning shows they are not needed in the DAG.

**To Reproduce**
files can be found in the dag_test branch.
This *should* work:
```
touch Jenkins/dag_fastqs/S1_1_R1.fastq.gz
touch Jenkins/dag_fastqs/S1_1_R2.fastq.gz
touch Jenkins_results/dedup/assembly2-S1_2.samtools-coordinate.bam

# adding these makes it work:
#touch Jenkins/dag_fastqs/S1_2_R1.fastq.gz
#touch Jenkins/dag_fastqs/S1_2_R2.fastq.gz

snakemake -n -j 10 --quiet -s workflows/alignment/Snakefile --directory workflows/alignment --configfile Jenkins/alignment/default_config.yaml --config samples=../../Jenkins/alignment/assemblies.tsv
```

**Expected behavior**
Ignore the samples if the downstream files are present

**Comment by Maarten-vd-Sande** [comment]
What do you mean with that the filelock complains? When I run it we get an error that the fastq files can not be found locally, so we can not infer paired-end or single-end. Is that what you mean?

**Comment by siebrenf** [comment]
Indeed. The layout is not important when starting from a bam file or counts table. So it would be nice if it would be omitted then. No idea how feasible that is however...

**Comment by Maarten-vd-Sande** [comment]
I am hoping this would never occur. Layout is still used for some quality metrics, and I think also some tracks in the trackhub. You'd have to parse it from the bam. You can check if the first N lines contain any paired-end flags. However that means another dependency in the "base" environment.

**Comment by siebrenf** [comment]
Then I suggest we make note in the docs that you need to touch the files in this edge-case, and leave it at that.

**Comment by Maarten-vd-Sande** [comment]
I highly doubt anyone ever using the pipeline like that + our current implementation will break on many places. I think mentioning this in the docs explicitly is just confusing. If someone already aligned they should just convert back to fastq and start from there. My 2c
