### ISSUE TITLE
BUG: Edge-case: messed up samples.tsv 

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#348]
**Describe the bug**
A mistake in your input samples.tsv can cause the layout file to remember a file as paired- or single-ended while it should be the other. This can cause errors with debug info like `cant find SE sample...` or `missing input for renamePE`. 

**Solution**
in `genomepy` Simon used a cache that times out after 7 days. If we use a 1 or 2 day cache system, the issue solves itself :)

**Comment by Maarten-vd-Sande** [comment]
We have `seq2science clean` for removing the cache
