### ISSUE TITLE
FR: configfiles are always supplemented

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#358]
**Describe the bug**
We currently load in `config.yaml` in every Snakefile (line 2). 

This means that a config added over the command line will always be supplemented by the config in the workflow directory. 
- This can cause issues if the latter has flags the former doesn't. 
- ~~Furthermore, I get an error certain vague cases: `AttributeError in [...]Snakefile: 'str' object has no attribute 'get'`~~

In the seq2science setting, the first point is the big issue: if we allow users to specify a config.yaml, it must not be supplemented by whatever is the workflow directory.

**Solution**
For each Snakefile, change

```
# complement the configuration
configfile: "config.yaml"

```
into
```
# complement the configuration if not provided over command line
if not workflow.overwrite_configfiles:
    configfile: "config.yaml"
```

this still allows the user to add flags via `--config`.

**Comment by siebrenf** [comment]
It seems the error is due to the content of the config file. The point still stands that this is required for CLI adding of configuration files.

**Comment by Maarten-vd-Sande** [comment]
Good catch, I think the way seq2science will be implemented we can just remove those lines.

**Comment by siebrenf** [comment]
that may be even better. there's more wrong with this than I thought. it doesn't catch the file added over the command line...
