### ISSUE TITLE
BUG: only options in the user-supplied config are unpacked by the config.smk

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#362]
**Describe the bug**
In the configuration we unpack dict-in-dict structures in the config, but only those from the user config(s)? options supplied over the command line are thereby not unpacked.

see configuration_generic.smk > everything to do with `user_config`

**Comment by Maarten-vd-Sande** [comment]
What happens in that part of the code is that user-provided paths are not automatically put inside results, and the non-user-provided paths are in results.

Can you provide a (failing) example?

**Comment by siebrenf** [comment]
I doesnt break anything, it just doesn't unpack them. as a result, they schema defaults are used and the config option is ignored.

`snakemake... --config quantifier=salmon decoy_aware_index=True` will have `decoy_aware_index=False`, as the field is ignored, and the schema default is used.

**Comment by Maarten-vd-Sande** [comment]
I do not see how user_config is related to that though

**Comment by Maarten-vd-Sande** [comment]
```
# make sure that difficult data-types (yaml objects) are in correct data format
for kw in ['aligner', 'quantifier', 'bam_sorter']:
    if isinstance(config.get(kw, None), str):
        config[kw] = {config[kw]: {}}

# validate and complement the config dict
for schema in config_schemas:
    validate(config, schema=f"../schemas/config/{schema}.schema.yaml")
```
Probably happens here then

**Comment by siebrenf** [comment]
no longer valid in seq2science
