### ISSUE TITLE
FR: scATAC test samples

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#366]
@JGASmits, could you provide a (set of) minimal sample(s) that can be used for testing?

**Comment by Maarten-vd-Sande** [comment]
I think I will write a script to generate those files for ATAC-seq anyways, so I could do it for scATAC & ChIP as well

**Comment by JGASmits** [comment]
My smallest files that can still generate a SNAPobject still take like 5 min to run succesfully

**Comment by Maarten-vd-Sande** [comment]
I am thinking about just making a really really small fastq and only keep 1 chromosome instead of full genome. Should speed things up considerably

**Comment by siebrenf** [comment]
if it works for rna-seq too we can throw out the old batch. they are too similar for differential gene expression anyway
