### ISSUE TITLE
BUG: creation of samtools environment fails

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#392]
**Describe the bug**

```
Creating conda environment /home/simon/anaconda3/envs/seq2science/lib/python3.7/site-packages/seq2science/rules/../envs/samtools.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /home/simon/anaconda3/envs/seq2science/lib/python3.7/site-packages/seq2science/rules/../envs/samtools.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - bioconda::samtools=1.10


Note that strict channel priority may have removed packages required for satisfiability.


  File "/home/simon/anaconda3/envs/seq2science/lib/python3.7/site-packages/snakemake/deployment/conda.py", line 342, in create
```

I have no clue why? I do have `channel_priority: strict` enabled in the conda config though.

**Comment by Maarten-vd-Sande** [comment]
Okay interesting. Can you try with version 1.9? :angel: 

Change here:
`/home/simon/anaconda3/envs/seq2science/lib/python3.7/site-packages/seq2science/envs/samtools.yaml`

**Comment by simonvh** [comment]
The channel priority in most of the environments is wrong.

Should be:

```
channels:
  - conda-forge
  - bioconda
  - defaults
```

Instead of:

```
channels:
  - bioconda
  - conda-forge
  - defaults
```

This wrong channel order cannot also result in obscure dependency errors.

**Comment by Maarten-vd-Sande** [comment]
When I change to strict, the tests start failing everywhere.. :scream: 

This is something we should discuss if we want to support. I think this might take a lot of time to do well. However it seems to be something that will stay:
> However, it may break old environment files, so we plan to delay making it conda's out-of-the-box default until the next major version bump, conda 5.0.

Maybe [boa](https://github.com/TheSnakePit/boa) might help in this process. I haven't taken a good enough look though.

**Comment by simonvh** [comment]
I don't understand what the problem would be? I have channel priority strict in my config and haven't noticed anything.

In any case, if it's tricky then leave this for now. Document it in the docs at a visible place that strict is currently not supported. Not worth time to support it for now.

Channel order as it is now with this PR is a good idea though.

**Comment by Maarten-vd-Sande** [comment]
I think it might be some strict + mamba issues.

So how did you get it to work in the end? Without strict? Or with a lower samtools version? Or changed the order of dependencies?
