### ISSUE TITLE
FR: option for --keep-going

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#396]
**Is your feature request related to a problem? Please describe.**

When a single task fails, the pipeline will stop. Normally with snakemake you can provide a `--keep-going` argument. There is the option to supply additional snakemake argument, but only in the `KEY=VAL` format.

**Describe the solution you'd like**

A way to specify `--keep-going`.

**Comment by Maarten-vd-Sande** [comment]
That would be 
`seq2science --snakemakeOptions keepgoing=True`

But the most-used options should be supported and adding this is trivial

**Comment by simonvh** [comment]
Adding this to the docs would already suffice for me :-). Good to know!

**Comment by simonvh** [comment]
Another one:

```
Building DAG of jobs...
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
/mnt/c/Users/simon/Documents/prj/test_seq2science/genomes/bosTau9/bosTau9_softmasking_unsorted.bed
```

Turns out the internal option is not called `rerun-incomplete` but `force_incomplete`. This works:

```
seq2science run atac_seq --cores 12 --snakemakeOptions force_incomplete=True
```

However, you have to look in the snakemake docs to find this.

**Comment by Maarten-vd-Sande** [comment]
Hmm, that's just sloppy mr. Köster :angel: . I will add it, thanks
