### ISSUE TITLE
BUG: Pipeline failed due to temporary files still being present.

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#405]
**Describe the bug**

Pipeline failed due to temporary files still being present.

```
$ cat results/log/samtools_presort/bosTau9-8-cell_rep1.log
[E::hts_open_format] Failed to open file "/data/test_seq2science/results/bwa-mem/bosTau9-8-cell_rep1.tmp.0000.bam" : File exists
samtools sort: failed to create temporary file "/data/test_seq2science/results/bwa-mem/bosTau9-8-cell_rep1.tmp.0000.bam": File exists
```

**Comment by Maarten-vd-Sande** [comment]
I thought this worked :cry:

**Comment by simonvh** [comment]
This was after another bug that crashed the pipeline (but that I didn't save the log output for).

**Comment by Maarten-vd-Sande** [comment]
Another bug?! :scream: 

But the solution is easy (removing those files beforehand as well opposed to only afterwards).

**Comment by simonvh** [comment]
I think it's this bug? I ran the pipeline again, after deleting the temp files, and it's the same error:

```
 $ cat results/log/samtools_presort/bosTau9-8-cell_rep1.log
[E::hts_open_format] Failed to open file "/data/test_seq2science/results/bwa-mem/bosTau9-8-cell_rep1.tmp.0000.bam" : File exists
samtools sort: failed to create temporary file "/data/test_seq2science/results/bwa-mem/bosTau9-8-cell_rep1.tmp.0000.bam": File exists
```

**Comment by Maarten-vd-Sande** [comment]
More importantly: why do you keep finding bugs :bug: ?! 

I can't really think of a situation where this would happen... Are you sure you deleted all temp files? Samtools makes a couple tmp files, and it will fail on the first it will find. However that is inconsistent with the error message as it seems to fail on the 0000 one.
