### ISSUE TITLE
BUG: Crash while installing packages

### ISSUE THREAD

**Issue by HNeikes** [vanheeringen-lab/seq2science#420]
**Describe the bug**
The pipeline crashes while downloading and installing packages:

Could not create conda environment from /home/hneikes/anaconda3/envs/seq2science/lib/python3.6/site-packages/seq2science/rules/../envs/edger.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound:
  - r::r-base=4.0.1

**Comment by Maarten-vd-Sande** [comment]
I get the same problem on my computer. :unamused: 

I fixed it and should be online somewhere later tonight

**Comment by Maarten-vd-Sande** [comment]
this is fixed in v0.0.3, thanks for reporting :)
