### ISSUE TITLE
BUG: chip_seq multiqc failed job

### ISSUE THREAD

**Issue by dzijlmans** [vanheeringen-lab/seq2science#439]
**Describe the bug**
Ran the seq2science chip_seq workflow. Workflow ran perfectly until it reached 106 out of 108 steps (98%), after which it threw an error while generating the multiqc report. The pipeline then terminated. Results folder contains all output files except multiqc report [so only minor inconvenience]. Enclosed please find multiqc log file. 

[multiqc_GRCm38.p6.log](https://github.com/vanheeringen-lab/seq2science/files/4966043/multiqc_GRCm38.p6.log)

Error message:
[Thu Jul 23 03:59:53 2020]
Error in rule multiqc:
    jobid: 2
    output: /home/dzijlmans/ChIP-seq/Kundu/results/qc/multiqc_GRCm38.p6.html, /home/dzijlmans/ChIP-seq/Kundu/results/qc/multiqc_GRCm38.p6_data
    log: /home/dzijlmans/ChIP-seq/Kundu/results/log/multiqc_GRCm38.p6.log (check log file(s) for error message)
    conda-env: /home/dzijlmans/anaconda3/envs/seq2science/lib/python3.7/site-packages/seq2science/.snakemake/e9b3e820
    shell:

        multiqc /home/dzijlmans/ChIP-seq/Kundu/results/bwa-mem/GRCm38.p6-GSM2393580.samtools-coordinate-unsieved.bam.mtnucratiomtnuc.json /home/dzijlmans/ChIP-seq/Kund38.p6-GSM2393580.samtools-coordinate.samtools_stats.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/samtools_stats/bwa-mem/GRCm38.p6-GSM2393592.samtools-coordinate.samtoundu/results/qc/macs2/GRCm38.p6-GSM2393592_featureCounts.txt.summary /home/dzijlmans/ChIP-seq/Kundu/results/bwa-mem/GRCm38.p6-GSM2393592.samtools-coordinate-unsieved.bChIP-seq/Kundu/results/qc/fastqc/GSM2393592_fastqc.zip /home/dzijlmans/ChIP-seq/Kundu/results/bwa-mem/GRCm38.p6-GSM2393579.samtools-coordinate-unsieved.bam.mtnucratiom/results/qc/markdup/GRCm38.p6-GSM2393580.samtools-coordinate.metrics.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/samtools_stats/final_bam/GRCm38.p6-GSM2393592.samtoozijlmans/ChIP-seq/Kundu/results/qc/macs2/GRCm38.p6-GSM2393584_featureCounts.txt.summary /home/dzijlmans/ChIP-seq/Kundu/results/qc/samtools_stats/final_bam/GRCm38.p6-GSats.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/samplesconfig_mqc.html /home/dzijlmans/ChIP-seq/Kundu/results/qc/trimming/GSM2393579.fastq.gz_trimming_report.txt /horimming/GSM2393580.fastq.gz_trimming_report.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/plotCorrelation/GRCm38.p6.tsv /home/dzijlmans/ChIP-seq/Kundu/results/qc/trimmtxt /home/dzijlmans/ChIP-seq/Kundu/results/qc/samtools_stats/final_bam/GRCm38.p6-GSM2393593.samtools-coordinate.samtools_stats.txt /home/dzijlmans/ChIP-seq/Kundu/resule/dzijlmans/ChIP-seq/Kundu/results/qc/fastqc/GSM2393584_fastqc.zip /home/dzijlmans/ChIP-seq/Kundu/results/qc/plotPCA/GRCm38.p6.tsv /home/dzijlmans/ChIP-seq/Kundu/resulip /home/dzijlmans/ChIP-seq/Kundu/results/qc/plotProfile/GRCm38.p6-macs2.tsv /home/dzijlmans/ChIP-seq/Kundu/results/macs2/GRCm38.p6-GSM2393592_peaks.xls /home/dzijlman-GSM2393593_peaks.xls /home/dzijlmans/ChIP-seq/Kundu/results/qc/markdup/GRCm38.p6-GSM2393584.samtools-coordinate.metrics.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/me/dzijlmans/ChIP-seq/Kundu/results/qc/macs2/GRCm38.p6-GSM2393593_featureCounts.txt.summary /home/dzijlmans/ChIP-seq/Kundu/results/qc/fastqc/GSM2393593_trimmed_fastqc.ts/qc/markdup/GRCm38.p6-GSM2393579.samtools-coordinate.metrics.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/trimming/GSM2393593.fastq.gz_trimming_report.txt /home/dziGSM2393593_fastqc.zip /home/dzijlmans/ChIP-seq/Kundu/results/qc/samtools_stats/bwa-mem/GRCm38.p6-GSM2393584.samtools-coordinate.samtools_stats.txt /home/dzijlmans/ChIP2393584.samtools-coordinate-unsieved.bam.mtnucratiomtnuc.json /home/dzijlmans/ChIP-seq/Kundu/results/qc/markdup/GRCm38.p6-GSM2393593.samtools-coordinate.metrics.txt /hsamtools_stats/final_bam/GRCm38.p6-GSM2393579.samtools-coordinate.samtools_stats.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/fastqc/GSM2393580_fastqc.zip /home/dzijlstats/final_bam/GRCm38.p6-GSM2393580.samtools-coordinate.samtools_stats.txt /home/dzijlmans/ChIP-seq/Kundu/results/macs2/GRCm38.p6-GSM2393579_peaks.xls /home/dzijlmans3579_fastqc.zip /home/dzijlmans/ChIP-seq/Kundu/results/qc/macs2/GRCm38.p6-GSM2393580_featureCounts.txt.summary /home/dzijlmans/ChIP-seq/Kundu/results/qc/markdup/GRCm38cs.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/fastqc/GSM2393579_trimmed_fastqc.zip /home/dzijlmans/ChIP-seq/Kundu/results/bwa-mem/GRCm38.p6-GSM2393593.samtools-coor /home/dzijlmans/ChIP-seq/Kundu/results/qc/trimming/GSM2393592.fastq.gz_trimming_report.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/samtools_stats/bwa-mem/GRCm38.p6-stats.txt /home/dzijlmans/ChIP-seq/Kundu/results/qc/samtools_stats/bwa-mem/GRCm38.p6-GSM2393593.samtools-coordinate.samtools_stats.txt /home/dzijlmans/ChIP-seq/Kundu/rxls /home/dzijlmans/ChIP-seq/Kundu/results/macs2/GRCm38.p6-GSM2393584_peaks.xls /home/dzijlmans/ChIP-seq/Kundu/results/qc/macs2/GRCm38.p6-GSM2393579_featureCounts.txt.esults/qc/fastqc/GSM2393584_trimmed_fastqc.zip -o /home/dzijlmans/ChIP-seq/Kundu/results/qc/ -n multiqc_GRCm38.p6.html         --config /home/dzijlmans/ChIP-seq/Kundu/                                          --config /home/dzijlmans/ChIP-seq/Kundu/results/qc/header_info.yaml                                                          q/Kundu/results/qc/sample_names_GRCm38.p6.tsv                                                --sample-filters /home/dzijlmans/ChIP-seq/Kundu/results/qc/sample_filters_                 --cl_config "extra_fn_clean_exts: [                                                    {'pattern': ^.*GRCm38.p6-, 'type': 'regex'},                    'regex'},                          ]" > /home/dzijlmans/ChIP-seq/Kundu/results/log/multiqc_GRCm38.p6.log 2>&1

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job multiqc since they might be corrupted:
/home/dzijlmans/ChIP-seq/Kundu/results/qc/multiqc_GRCm38.p6.html, /home/dzijlmans/ChIP-seq/Kundu/results/qc/multiqc_GRCm38.p6_data
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dzijlmans/ChIP-seq/Kundu/.snakemake/log/2020-07-23T002330.613210.snakemake.log

**To Reproduce**

**config.yaml**
samples: samples.tsv

result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes

email: d.zijlmans@science.ru.nl

create_trackhub: True

peak_caller:
  macs2:
      --keep-dup 1 --buffer-size 10000

biological_replicates: fisher  # change to "keep" to not combine them
technical_replicates: merge    # change to "keep" to not combine them

remove_blacklist: True
min_mapping_quality: 30
only_primary_align: True

**samples.tsv**

sample	assembly	descriptive_name
GSM2393579	GRCm38.p6	ring1b
GSM2393580	GRCm38.p6	phc1
GSM2393584	GRCm38.p6	ezh2
GSM2393592	GRCm38.p6	input1
GSM2393593	GRCm38.p6	input2

**Expected behavior**

**Screenshots**

**Comment by Maarten-vd-Sande** [comment]
I am not sure either. Before when it would fail here there were issues with the descriptive_name column. This looks just fine.

I will take a look when I'm back. 

In general: the deeptools stuff is quite prone to errors :(

**Comment by Maarten-vd-Sande** [comment]
The rest of the files are safe to use at least

**Comment by Maarten-vd-Sande** [comment]
When I run it with the newest version everything seems to work! Can you try again with the newest version and in a new directory (so no old files remain)?

**Comment by Maarten-vd-Sande** [comment]
Also works for Dick :)
