### ISSUE TITLE
FR: switch to pysradb (investigate feasibility) for checking layout

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#445]
**Is your feature request related to a problem? Please describe.**
I dont want to wait for the lookup of sample layouts anymore!

**Describe the solution you'd like**
Seems like pysradb has the option to check for sample layout. Might be nice to switch :)
https://github.com/saketkc/pysradb
https://saket-choudhary.me/pysradb/python-api-usage.html#use-case-1-fetch-the-metadata-table-sra-runtable

No clue how well this works though.

**Comment by Maarten-vd-Sande** [comment]
pysradb requires you to download a 25 gigabyte sqlite database before usage.....

Maybe not the best idea

**Comment by saketkc** [comment]
Hi @Maarten-vd-Sande, Just to clarify, `pysradb` does not require `SRAmetadb.sqlite` downloads anymore (and hasn't required so for a while now). 

You can checkout the Colab notebooks for demonstration of the web based API:  https://github.com/saketkc/pysradb/tree/master/notebooks

P.S. I discovered this repo via Github. Seq2Science looks cool!

**Comment by Maarten-vd-Sande** [comment]
Hi @saketkc, this is quite a coincidence!!! 

Just yesterday I discovered the `SRAweb` class and I have been working on implementing it in seq2science :tada:, since it works much nicer than the e-utils api. 

One question, but maybe I should make an issue about it, the `library_layout` seems to be missing. However in the docs they are [there](https://saket-choudhary.me/pysradb/usage_scenarios.html#scenario-1) when using the detailed flag. I am using version `0.11.0`. Also in the notebooks they seem to be missing.
