### ISSUE TITLE
FR: Include ERCC spike-ins in scRNA-seq index build

### ISSUE THREAD

**Issue by Rebecza** [vanheeringen-lab/seq2science#450]
**Missing feature**
Our samples are mostly processed with the use of ERCC spike-in RNA mix (https://www.thermofisher.com/order/catalog/product/4456740#/4456740), if mapped, these can be used downstream for QC and normalization purposes.  

**Solution**
Consider adding the ERCC to the genome and annotation file before building the reference within the workflow, since this mix is generally used in our lab.

**Comment by Maarten-vd-Sande** [comment]
@siebrenf any clue if something like this works?

```
genomepy install mygenome.fa url
```

If so we could make a new workflow that prepares the fasta in case people have their own custom one. @quan-xu had this issue also before with some xenopus genome.

**Comment by siebrenf** [comment]
The current system already allows people to place their own genome + annotation files in the `genome_dir`, which may include spike-ins.

The most elegant solution (IMO) to expand this, is to allow people to add a spike-in file to the `config.yaml`. If it is detected, we then 
1) copy the genome to a new folder, 
2) add the spike ins (its just concatenated IIRC)
3) make an index in this folder
4) tell aligners to use this index.

the result is that spike-in genomes are automatically generated and kept separate from the original

**Comment by Maarten-vd-Sande** [comment]
Yes that would work.

The current system sucks for working with your own genomes, because you would have to make the .fa.sizes, .fa.fai, and gaps.bed yourself.
