### ISSUE TITLE
BUG: snakemakeoptions parsing

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#507]
**Describe the bug**
seq2science run atac-seq --snakemakeOptions cluster="sbatch dsadas dsadsada dsadsa dasdsa" should work

**Comment by siebrenf** [comment]
It does(?)

`seq2science run atac-seq -n --snakemakeOptions cluster="sbatch dsadas dsadsada dsadsa dasdsa"` is converted to the following `parsed_args`:
```
{'snakefile': '/home/siebrenf/git/seq2science/seq2science/workflows/atac_seq/Snakefile', 'use_conda': True, 'conda_frontend': 'mamba', 'conda_prefix': '/home/siebrenf/git/seq2science/seq2science/.snakemake', 'dryrun': True, 'printreason': False, 'keepgoing': False, 'unlock': False, 'force_incomplete': False, 'cluster': 'sbatch dsadas dsadsada dsadsa dasdsa', 'config': {'rule_dir': '/home/siebrenf/git/seq2science/seq2science/rules', 'cores': 999}, 'configfiles': ['/home/siebrenf/git/seq2science/./config.yaml'], 'cores': 999}
```
This seems compatible with the [snakemake API](https://snakemake.readthedocs.io/en/stable/api_reference/snakemake.html)

Running the command yields the following error, which seems OK to me: 
```
sbatch: error: Unable to open file dsadas
Error submitting jobscript (exit code 1):
```

**Comment by Maarten-vd-Sande** [comment]
oh! Maybe I was using an older version?!

**Comment by Maarten-vd-Sande** [comment]
I got the problem that it was separating them by spaces

**Comment by Maarten-vd-Sande** [comment]
I will retry in a bit
