### ISSUE TITLE
BUG: multiqc with many samples

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#513]
**Describe the bug**
I am not sure how responsive the html will be with many samples, but s2s really shouldn't crash! If we move all qc stuff in a folder per assembly, it should work. However, this will also add qc from previous runs. Do/should we care?

**Comment by siebrenf** [comment]
we could generate a hash based on the samples.tsv (and the config.yaml?) to create run specific multiqc folders (assembly_{hash}).

**Comment by Maarten-vd-Sande** [comment]
Perhaps writing all required files in a file, and using xargs works? :thinking: 

This would be a less_intrusive way of doing it. Might still need the hash though

**Comment by Maarten-vd-Sande** [comment]
https://github.com/vanheeringen-lab/seq2science/issues/513
