### ISSUE TITLE
BUG: 'layout' not found

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#526]
**Describe the bug**

```
Checking if samples are available online...
This can take some time.
Done!


KeyError in line 382 of /vol/mbconda/heeringen/envs/seq2science/lib/python3.8/site-packages/seq2science/rules/configuration_generic.smk:
'layout'
  File "/vol/mbconda/heeringen/envs/seq2science/lib/python3.8/site-packages/seq2science/workflows/atac_seq/Snakefile", line 4, in <module>
  File "/vol/mbconda/heeringen/envs/seq2science/lib/python3.8/site-packages/seq2science/rules/configuration.smk", line 1, in <module>
  File "/vol/mbconda/heeringen/envs/seq2science/lib/python3.8/site-packages/seq2science/rules/configuration_generic.smk", line 382, in <module>
```

**To Reproduce**

samples.tsv

```
sample  descriptive_name        replicate       assembly
GSM3215609      GM12878 bulk NT1 Rep1   GM12878 hg38
GSM3215610      GM12878 bulk NT1 Rep2   GM12878 hg38
GSM3215611      GM12878 bulk NT1 Rep3   GM12878 hg38
```

**Expected behavior**

In order of preference: a normal run,  a warning.

**Comment by Maarten-vd-Sande** [comment]
Which version are you using?

`seq2science --version`

Can you try

`seq2science clean`

and then try again?

**Comment by Maarten-vd-Sande** [comment]
These samples have no SRA on them (maybe protected e.g. dbGaP)? https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3215609

When I try it with the newest version I get:

```
Checking if samples are available online...
This can take some time.
No results found for ['GSM3215609', 'GSM3215610', 'GSM3215611']
We had trouble querying the SRA. This probably means that the SRA was unresponsive, and their servers are overloaded or slow. Please try again in a bit...
```

But that is not a good error message for missing data

**Comment by simonvh** [comment]
This is on the latest conda version.  Should I use a newer one?

This is actually already a better message, you see the GSM's so you can remove them.

**Comment by Maarten-vd-Sande** [comment]
I actually checked with the `develop` version, but this code has not been changed since the latest release. If you have the latest version then I potentially made a mistake with uploading to conda

Please check if you are on v0.3.0 to be sure
`seq2science --version`
