### ISSUE TITLE
BUG: complement blacklist fails, .fa.sizes empty

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#534]
**Describe the bug**
Reported by Branco (hg38), but now I (GRCg6a) have it as well. 

The .fa.sizes file is empty... :thinking:

**Comment by Maarten-vd-Sande** [comment]
I guess its related to this:

```
        genomepy.Genome(wildcards.assembly, genomes_dir=config["genome_dir"])
        # snakemake doesnt wait until the above command finished running without this...
        shell("touch {output[3]}")
```

@siebrenf maybe we should just put a sleep there?

**Comment by Maarten-vd-Sande** [comment]
When I run until `get_genome_support_files` it seems to be doing fine

**Comment by siebrenf** [comment]
I think this is indeed the problem. Which is double weird as I thought this `touch` fixed it!
The required time is variable (genome.fa.fai generation time depends on the genome size), so a sleep wont do (and its really ugly).

I have 2 workarounds, but no solution to the actual problem...

**Comment by Maarten-vd-Sande** [comment]
I have a solution I think. I will have to test it still.

**Comment by siebrenf** [comment]
that's a workaround, but honestly, its better than my ideas (a checkpoint or ambiguous outputs).

I'm not certain it will work: in genomepy, the files are opened, and then filled ([link](https://github.com/vanheeringen-lab/genomepy/blob/a75d791b9fbd1a772503b370c0472dbe4744d974/genomepy/utils.py#L101)). weirdly enough however, I expect the gaps_file to be made last, so i would expect that one to be empty... so maybe it works!

The solution would be to make snakemake wait for the genomepy script to be completed.

**Comment by Maarten-vd-Sande** [comment]
I could change the check to check if it hasn't been updated for at least a second? Might be more robust?

**Comment by siebrenf** [comment]
that... could work!
