### ISSUE TITLE
BUG: sample clustering image no letters

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#543]
**Describe the bug**
A clear and concise description of what the bug is. Please add the (full) error message.
![image](https://user-images.githubusercontent.com/15323399/97492361-b7245380-1963-11eb-9e1d-474d048909a6.png)

**Comment by siebrenf** [comment]
that's pretty concise

**Comment by siebrenf** [comment]
This is both dumber, and more complex than I thought...

To import this image in MultiQC it must be output as a .png file. R's `png()` (and `svg()` too for that matter) uses some kind of encoding for this that is apparently not supported on the platform you're running on (I've seen this before on mbscourse as well, but on my PC it's fine). I _think_ this encoding is `latin-1`.

The kicker is: rendering the image as pdf with R's `pdf()` does work. 

Ok, so lets output as pdf and convert to png?
[This R package is not on conda](https://rdrr.io/github/jefferis/paperutils/man/pdf2png.html), neither is [this package](https://www.rdocumentation.org/packages/TraMineRextras/versions/0.4.5/topics/convert), and installing R packages from github is not possible through conda, and both slow and unreliable in R. 
In Ubuntu, there is `convert`, but this relies on a [completely disabled script that requires root rights to fix](https://askubuntu.com/questions/1081895/trouble-with-batch-conversion-of-png-to-pdf-using-convert).

I have one potential solution, which is to install r-cairo, a library which allows `png()` to use its encoring method. Could you try if that solves it?

**Comment by Maarten-vd-Sande** [comment]
![image](https://user-images.githubusercontent.com/15323399/98031424-c1869780-1e12-11eb-9078-3c1dc9a463b2.png)
