### ISSUE TITLE
BUG: pysradb API rate exceeded

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#552]
**Describe the bug**
https://github.com/vanheeringen-lab/seq2science/pull/550#issuecomment-721250179

**Fix**
https://github.com/vanheeringen-lab/seq2science/pull/550#issuecomment-721289955

**Comment by Maarten-vd-Sande** [comment]
I'm thinking this might be related to our parallel stuff, since so far I have only seen it in the parallel part of the test

**Comment by Maarten-vd-Sande** [comment]
Also happens in the docs, which should not do anything in parallel, and also is not parallel :thinking:

**Comment by Maarten-vd-Sande** [comment]
Closing because I haven't seen this in a while
