### ISSUE TITLE
FR: trim down base env

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#574]
**Is your feature request related to a problem? Please describe.**
We could/should clean up our base env by moving the run directives to scripts.

- [ ] rule trackhub, package(s): trackhub, biopython, matplotlib
- [ ] rule multiqc_samplesconfig, package(s): pretty_html_table
- [ ] rule keep_mates, package(s): pysam

**Comment by siebrenf** [comment]
I'm not sure trackhub can be moved to a script :/

The rule requires an input function, which is now the same function that creates the hub. I combined the two to remove the double logic in determining which files are needed. 

This means that trackhub functionality is everywhere, and the input function cannot work without importing trackhub. 
Unless I'm missing something with inputfunctions (or if there is a pythonic way of ignoring all errors in an inputfunction).

**Comment by Maarten-vd-Sande** [comment]
Ah I conveniently overlooked that bit. It's possible, but probably not worth our time.
