### ISSUE TITLE
BUG: GRCh38.p13.customblacklist_complement

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/seq2science#584]
**Describe the bug**

He doesnt seem to find the correct blacklist file.
/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Epi_fate_specifiers/genomes/GRCh38.p13/GRCh38.p13.customblacklist_complement.bed

> Traceback (most recent call last):
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/__init__.py", line 699, in snakemake
>     keepincomplete=keep_incomplete,
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/workflow.py", line 937, in execute
>     success = scheduler.schedule()
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/scheduler.py", line 394, in schedule
>     run = self.job_selector(needrun)
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/scheduler.py", line 541, in job_selector
>     c = list(map(self.job_reward, jobs))  # job rewards
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/scheduler.py", line 623, in job_reward
>     temp_size = self.dag.temp_size(job)
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/dag.py", line 556, in temp_size
>     return sum(f.size for f in self.temp_input(job))
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/dag.py", line 556, in <genexpr>
>     return sum(f.size for f in self.temp_input(job))
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/io.py", line 139, in wrapper
>     return func(self, *args, **kwargs)
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/io.py", line 154, in wrapper
>     return func(self, *args, **kwargs)
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/io.py", line 350, in size
>     return self.size_local
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/io.py", line 355, in size_local
>     self.check_broken_symlink()
>   File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.7/site-packages/snakemake/io.py", line 360, in check_broken_symlink
>     if not self.exists_local and os.lstat(self.file):
> FileNotFoundError: [Errno 2] No such file or directory: '/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Epi_fate_specifiers/genomes/GRCh38.p13/GRCh38.p13.customblacklist_complement.bed'
> 

I've looked into GRCh38.p13, and there is a blacklist file however this is called:
"GRCh38.p13.blacklist.bed"

I've copied this and renamed it to Ch38.p13.customblacklist_complement.bed, and am running it now to see if this solves it.

My sample file is located at: /ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Epi_fate_specifiers/RNAseq/samples.tsv

and my config file at:
/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/Epi_fate_specifiers/RNAseq/config.yaml

Greetings :)

**Comment by Maarten-vd-Sande** [comment]
This seems different than what Vicky had last week. Vicky's version did not unpack the blacklist.

Something fishy going on here :(

**Comment by JGASmits** [comment]
I think the problem was me running multiple pipelines in parallel, using the same genome! Running them 1 by 1 seems to stop this issue from happening.
