### ISSUE TITLE
BUG: duplicate rows in count table

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#587]
**Describe the bug**
```
Warning message:
package ‘edgeR’ was built under R version 3.6.2 
```

**To Reproduce**
I ran the atac-seq pipeline with default settings

**Comment by siebrenf** [comment]
It's a minor issue.

r::r-base is 3.6.1 max, but some of the bioconda packages are built on 3.6.2. I haven't gotten any errors because of this.
Without rstudio, I've had some success with conda-forge::r-base version 4+, should updating really be needed.

**Comment by Maarten-vd-Sande** [comment]
The rule failed. I assumed this was the reason. But when I just ran it to check where the log is it just ran.... :thinking:

**Comment by Maarten-vd-Sande** [comment]
My bad, this was another issue:

```
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed
Calls: read.delim -> read.table
Execution halted
```
```
>>> len(df.index)
63506
>>> len(set(df.index))
63504

```

**Comment by siebrenf** [comment]
Try conda-forge::r-base=4.0.3 if you get R related issues. Might be able to pin the chipseeker version too!

**Comment by Maarten-vd-Sande** [comment]
This can happen on the edge of a chromosome :thinking:
