### ISSUE TITLE
FR: RNA-seq RSeQC

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#588]
**Is your feature request related to a problem? Please describe.**
Unnecessary, but might be nice if someone has the time

http://rseqc.sourceforge.net/

Seems to be integratable with multiqc, and adds awesome stuff like juntions to UCSC genome browser. Not sure if its supported by trackhub
![image](https://user-images.githubusercontent.com/15323399/100334465-1d88aa00-2fd4-11eb-92e2-b4495ec9a826.png)

**Comment by siebrenf** [comment]
we already use the package for strandedness! I'll have a look next time I'm in a programming mood ;)
