### ISSUE TITLE
FR: rRNA removal

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#590]
**Is your feature request related to a problem? Please describe.**
@tilschaef told me about filtering out rRNA for RNA-seq, and this seems like a sane thing to do. Multiple tools exist that do this. These generally require a rRNA database to work. I don't think we can somehow extract this info from the gtf file @siebrenf ?

**Comment by Maarten-vd-Sande** [comment]
http://hulab.ucf.edu/research/projects/rRNAFilter/rRNAFilter.html does not require a database..

**Comment by tilschaef** [comment]
We could use SortMeRNA (https://bioinfo.lifl.fr/RNA/sortmerna/) which automatically downloads the most recent SILVA rRNA databases . You do not have to extract any tracks from gtf since they are frequently absent from genome annotations for certain species.

**Comment by Maarten-vd-Sande** [comment]
That seems nice. How would we specify which database to use? Another option in the config?

**Comment by tilschaef** [comment]
SortMeRNA requires no specification of the assembly, it is always the same set of fasta files containing the ribosomal sequences (across multiple domains). The reads that align are written to a separate fastq file.

**Comment by siebrenf** [comment]
Ensembl GTF files contain the 'gene_biotype' field, which specifies if the gene is ribosomal or tRNA ([link](http://www.ensembl.org/info/genome/genebuild/biotypes.html))

```
(base) siebrenf@passer:~$ cat .local/share/genomes/GRCh38.p13/GRCh38.p13.annotation.gtf | grep tRNA
MT      insdc   gene    577     647     .       +       .       gene_id "ENSG00000210049"; gene_version "1"; gene_name "MT-TF"; gene_source "insdc"; gene_biotype "Mt_tRNA";
```

A [trip to biostars](https://www.biostars.org/p/87260/) suggested to either remove these reads from the gtf when quantifying, or to filter them out afterward. Either way, we should still align them to something, and then filter them out.

P.S. I think [decoy aware salmon](https://salmon.readthedocs.io/en/latest/salmon.html) is an assembly-independent approach to this problem. It creates a set of highly repetitive RNA & DNA sequences before mapping, then subtracts all reads mapped to the decoy regions. This is already possible in s2s!

**Comment by Maarten-vd-Sande** [comment]
I am not sure if the decoy is the same. I am absolutely not an expert on RNA-seq, but the way I understand it, the decoy should help with overrepresented sequences in the genome+transcriptome:

> to mitigate potential spurious mapping of reads that actually arise from some unannotated genomic locus that is sequence-similar to an annotated transcriptome.

The docs nowhere mention anything that this helps against rRNA

**Comment by tilschaef** [comment]
@siebrenf  filter them out is surely a good idea, however 'gene_biotype' fields are not always annotated. You can circumvent that by using some annotation agnostic filtering approaches, such as SortMeRNA or rRNAFilter.
