### ISSUE TITLE
BUG: [scRNA: Trimming inconsistencies ]

### ISSUE THREAD

**Issue by tilschaef** [vanheeringen-lab/seq2science#593]
**Describe the bug**
Trimming of scRNA reads before running kallisto bustools does not produce expected results. Since we only trim the fastq that contains the reads, the number of total reads after trimming can vary between R1/R2.  

**To Reproduce**
The current implementation of the seq2science scRNA workflow can not reproduce the results from the [10xv3 pbmc notebook](https://colab.research.google.com/github/pachterlab/kallistobustools/blob/master/notebooks/kb_analysis_0_python.ipynb#scrollTo=bEN8ifXwEbki). This becomes especially apparent in the PCA plot which displays no cluster structure but appears random.

**Expected behavior**
The count tables produces by the scRNA workflow should yield comparable results to the 10xv3 pbmc notebook.  

**Possible solution**
Add a fastq matching rule after trimming to correct for differing read numbers between R1 and R2. This could be archived with (fastq-pair)[https://github.com/linsalrob/fastq-pair]

**Comment by Maarten-vd-Sande** [comment]
Potential fix through pyfastx: https://github.com/lmdu/pyfastx/issues/22

However my current implementation is **slow**, so not attractive. Hopefully I am just being stupid.
