### ISSUE TITLE
BUG: column names in samples.tsv

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/seq2science#597]
**Describe the bug**

Not really a bug, but something that I think should be fixed. Currently the `replicate` columns in `samples.tsv` describes *technical replicates*, while the `condition` columns describes *biological replicates*. If I understand the docs correctly. I think this naming should be improved. My hunch is that most people will expect a replicate to be a biological replicate. You can also see this for replicates on GEO. These are pretty much always **biological** replicates, that you would not expect to be merged. The term `condition` is used when a sample is treated, a gene is knocked-out etc. So, I think this is confusing. Could we not be explicit and name these columns `technical_replicate` and `biological_replicate`? All `samples.tsv` examples in the docs (which are great btw), should contain some biological replicate examples, and not an example of just technical replicates.

**Comment by siebrenf** [comment]
We opted for these names long ago because your suggestions seemed to long. But we could just add these columns to the default samples.tsv!

Any objections Maarten?

**Comment by Maarten-vd-Sande** [comment]
I'm always pro making this more clear! I think the proposed changes make sense, should be easy to implement.
