### ISSUE TITLE
BUG: NotADirectoryError

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#604]
Can't really say how this happened (student), but I am putting this one here for the sake that we are aware of it.

![image](https://user-images.githubusercontent.com/15323399/101651997-f901e880-3a3d-11eb-8355-45de9c98f5a8.png)

**Comment by siebrenf** [comment]
os.remove(file) shouldn't be able to throw that error... witchcraft!

**Comment by Maarten-vd-Sande** [comment]
It's really weird:
https://github.com/snakemake/snakemake/blob/v5.18.1/snakemake/io.py#L665-L669

**Comment by Maarten-vd-Sande** [comment]
I guess the problem is that snakemake=5.18 does not work with Python above 3.6?
