### ISSUE TITLE
FR: check for duplicate yaml keys

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#605]
**Is your feature request related to a problem? Please describe.**
Some people (@JGASmits kuch kuch) put multiple of the same keys in the `config.yaml`. QOL fix to add a check for this.

**Comment by Maarten-vd-Sande** [comment]
Hmmm... The config is parsed by snakemake :thinking:

**Comment by JGASmits** [comment]
SHAME..... ding..... SHAME..... ding...... SHAME

**Comment by Maarten-vd-Sande** [comment]
![Uploading image.png…]()

**Comment by siebrenf** [comment]
![image](https://user-images.githubusercontent.com/48289046/112630376-cd144280-8e35-11eb-883c-4730cbf35bf4.png)

insert "issues from duplicate config keys"
