### ISSUE TITLE
BUG: Missing required 'bigDataUrl' setting in hub http://ocimum.science.ru.nl/trackhub_rna/RNA-seq_trackhub.hub.txt genome hub_63620_UCB_Xtro_10.0 track reversestrandreads

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#611]
**Describe the bug**
I can't visualize my RNA trackhub :sob: 

It's here: http://ocimum.science.ru.nl/trackhub_rna/

**Comment by Maarten-vd-Sande** [comment]
Removing that track from the hub solved it. It seems like it is missing tracks

**Comment by siebrenf** [comment]
it seems my implementation doesnt work with unstranded data!

untill a fix is live, you can manually fix the trackhub by opening the `trackDb.txt` and removing the last stanza. It should look (roughly) like this:

```
    track reversestrandreads
    shortLabel rev reads
    longLabel reverse strand reads
    type bigWig
    maxHeightPixels 100:50:8
    parent RNAseqsamples
    view reverse
    visibility full
```
