### ISSUE TITLE
`InputFunctionException in line 262 of /seq2science/lib/python3.8/site-packages/seq2science/rules/quantification.smk:

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/seq2science#633]
**Describe the bug**
If I run s2s (rnaseq pipeline), everything works.
However if I then add new samples to the sample.csv file, and try to rerun the workflow (to map the newly added samples), s2s rnaseq crashes:

`InputFunctionException in line 262 of /vol/mbconda/jsmits/envs/seq2science/lib/python3.8/site-packages/seq2science/rules/quantification.smk:
IndexError: index 0 is out of bounds for axis 0 with size 0
Wildcards:
assembly=GRCh38.p13
sample=GSM438361
  File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 111, in run_jobs
  File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 402, in run
  File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 203, in _run
  File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 131, in _run
  File "/vol/mbconda/jsmits/envs/seq2science/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 137, in printjob`

However if i rerun the pipeline with all the samples (so remove all the previously generated output), it runs withouth a problem.
This happend 2x with exactly the same error, both times I added new samples tot he sample file which caused it to crash (but run when rerunning everything).

Right now I'm running s2s with the new samples. Once this is finished ill try to generate a 2 sample sample file that can reproduce this error. This is not needed to be fixed soon, but i put this here for if somebody else encounters this. :)

**Comment by Maarten-vd-Sande** [comment]
This might be something that needs to be adressed in #585 since we are adding "rerunning" stuff (which should fix all your problems!)

**Comment by Maarten-vd-Sande** [comment]
@JGASmits p.s. currently we do not really support changing the samples file and that s2s figures out what needs to be done. That will be supported in the next release though..

**Comment by JGASmits** [comment]
Hahaha, I'm getting spoiled by the functionality of s2s

**Comment by Maarten-vd-Sande** [comment]
Let's keep it open so I don't forget to check if this works next release :smile:

**Comment by Maarten-vd-Sande** [comment]
@JGASmits which version were you using?

**Comment by Maarten-vd-Sande** [comment]
never mind found the bug

**Comment by siebrenf** [comment]
How does the fix work? Does it causes the checkpoint to always re-evaluate or something?

**Comment by Maarten-vd-Sande** [comment]
Hmm... Never mind. Thinking about it, it actually does not resolve the error (it does solve a potential edge-case for the rerun PR)...

I am not entirely sure how to fix that actually :thinking:

**Comment by Maarten-vd-Sande** [comment]
Perhaps a simple check if some output is there before indexing might work? Might work together with the rerun branch, I will test later

**Comment by Maarten-vd-Sande** [comment]
@JGASmits can you try if the rerun branch works?

```
pip install git+https://github.com/vanheeringen-lab/seq2science.git@rerun
```

You will need to completely run everything from start. So once with less samples, then add some samples, then start the run again. I _think_ that this works....

**Comment by JGASmits** [comment]
I'll try it out this afternoon!

**Comment by Maarten-vd-Sande** [comment]
@JGASmits How did it go? :innocent:
