### ISSUE TITLE
BUG: `seq2science -r` doesn't output reason without `--skip-rerun`

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#654]

**Comment by Maarten-vd-Sande** [comment]
That's strange, I don't see any apparent reason for it..

When you use targets / force, snakemake does not output reason anymore?

**Comment by siebrenf** [comment]
I think the reason argument does not carry over to the 2nd (real) run

**Comment by Maarten-vd-Sande** [comment]
Ah.. Might be related to `parsed_args["keep_logger"]`!
