### ISSUE TITLE
FR: fastq naming convention

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#660]
**Is your feature request related to a problem? Please describe.**
Fastq files are currently made with a "new" extension: https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/NamingConvention_FASTQ-files-swBS.htm ending with 001

Should we change our fqext settings? Or should we auto-detect this somehow? :thinking:

**Comment by siebrenf** [comment]
I thought we actually were auto detecting this with [get_wrong_fqext()](https://github.com/vanheeringen-lab/seq2science/blob/4b20270767805c73ffd01a32026f40c2ef7ec545/seq2science/rules/get_fastq.smk#L136). Should be expandable.

Is this the default Illumina output now?

**Comment by Maarten-vd-Sande** [comment]
I don't know..

**Comment by Maarten-vd-Sande** [comment]
@siebrenf this is now fixed right?

**Comment by siebrenf** [comment]
yarp
