### ISSUE TITLE
FR: markduplicates and primary align defaults

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#664]
> repetitive reads (multi-mappers) should **not** be removed from the BAM. If that happens, that should change in the pipeline.
> While in general we discard them (for TF ChIP-seq) there are ways to use them, as is the case in Stefan's project.
> So they should be present in the final BAM (though marked as multi-mapper)
> This is for the BAMs though. Default setting for bigWigs should be to remove both multimappers as well as duplicates.
> The primary alignment (picked at random) will not have flag 256 set, but will have a mapq of 0

Easy enough to revert this (we changed to remove duplicates by default in 0.3.0). Not sure how we can circumvent the `mapq` problem (in that filtering for mapq seems nice)

**Comment by Maarten-vd-Sande** [comment]
Macs2 documentation (is gone btw :shrug:) is completely unclear about which reads are considered for peak calling and which arent (this is relevant for the resulting bigwigs). Some old discussion: https://groups.google.com/g/macs-announcement/c/ASQ3GsXQC1c

Not looking forward to have a pre-sieve bam, post-sieve bam, and a peak-call bam...

**Comment by Maarten-vd-Sande** [comment]
Also not sure how e.g. `gimmemotifs.coverage_table` works with those "unfiltered" bams

**Comment by Maarten-vd-Sande** [comment]
Perhaps a single flag that sets it to keep everything (but marked) and also a FAQ entry? :thinking:

**Comment by siebrenf** [comment]
not the way we want to implement this, but on the bigwig side its achieved with this:
```
  deeptools_flags:
    description: flags for bam to bigwig conversions with deeptools bamCoverage. Bins Per Million mapped reads is roughly the same as TPM in RNA-seq.
    default: '--normalizeUsing BPM --samFlagExclude 1024 --minMappingQuality 1'
```

**Comment by Maarten-vd-Sande** [comment]
Yes, however the bigwigs are generated by macs2/genrich when you use those for peak calling....!

**Comment by Maarten-vd-Sande** [comment]
@siebrenf perhaps it's possible to add the result of `seq2science explain` at the top of the multiqc report? That would be kinda nice I guess?
