### ISSUE TITLE
BUG: edgeR normalization

### ISSUE THREAD

**Issue by HNeikes** [vanheeringen-lab/seq2science#666]
**Describe the bug**
My seq2science chip-seq pipeline keeps crushing during edgeR normalization, with error messages during different kinds of normalization steps.

**config.yaml:**
```# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: /ceph/rimlsfnwi/data/molbio/vermeulen/hneikes/databases/genomes  # where to look for or download the genomes
fastq_dir: /scratch/hneikes/oc2/fastq/


# contact info for multiqc report and trackhub
email: h.neikes@science.ru.nl

# produce a UCSC trackhub?
create_trackhub: True

# how to handle replicates
biological_replicates: fisher  # change to "keep" to not combine them
technical_replicates: merge    # change to "keep" to not combine them

fqext1: R1_001
fqext2: R2_001

# which trimmer to use
trimmer: fastp

# which aligner to use
aligner: bwa-mem

# filtering after alignment
remove_blacklist: True
min_mapping_quality: 30
only_primary_align: True

# peak caller
peak_caller:
  macs2:
      --keep-dup 1 --buffer-size 10000
```

[mm10-macs2-TMM.log](https://github.com/vanheeringen-lab/seq2science/files/6155140/mm10-macs2-TMM.log)
[mm10-macs2-upperquartile.log](https://github.com/vanheeringen-lab/seq2science/files/6155141/mm10-macs2-upperquartile.log)
[mm10-macs2-RLE.log](https://github.com/vanheeringen-lab/seq2science/files/6155142/mm10-macs2-RLE.log)

**Comment by Maarten-vd-Sande** [comment]
Oh no :cry: 

Which version of seq2science is this: `seq2science --version`?

**Comment by HNeikes** [comment]
it's version v0.3.1

**Comment by Maarten-vd-Sande** [comment]
If possible, try updating to v0.5.0, and see if somehow that magically resolves the problem.

**Comment by HNeikes** [comment]
That magic didn't work unfortunately :(
