### ISSUE TITLE
FR: version number in log

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#673]
Print the version of seq2science either at the beginning or end of the run, otherwise some people get confused with what they did

kuch kuch :roll_eyes: @Rebecza

**Comment by siebrenf** [comment]
doesnt that happen here? https://github.com/vanheeringen-lab/seq2science/pull/665

**Comment by Maarten-vd-Sande** [comment]
No, it is already in the QC report. But would be nice to print it also to stdout (and thus in the seq2science log file) for when people do not make qc reports.
