### ISSUE TITLE
BUG: Warning: the following output files of rule get_genome_support_files were not present when the DAG was created:

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#682]
**Describe the bug**
Seems like genomepy automatically makes the .fa.sizes file? @siebrenf is this likely? I can test somewhere these days with the --until flag

**Comment by siebrenf** [comment]
yes, it does in [get_genome_support_files](https://github.com/vanheeringen-lab/seq2science/blob/0542a671d06f301d48a67a484cf21ad991affbf3/seq2science/rules/get_genome.smk#L104), which calls [this script](https://github.com/vanheeringen-lab/seq2science/blob/master/seq2science/scripts/genome_support.py).

**Comment by Maarten-vd-Sande** [comment]
Ah yes, sorry unclear from my part. But I think the `get_genome` rule already makes this file, because when the `get_genome_support_files` rule starts, it prints a warning that the .fa.sizes already exists.

**Comment by siebrenf** [comment]
it should! I made this into a separate rule in case you already have the genome fasta or extend it. 

We could leave the warning, or implement a silly fix: remove these files at the end of the `get_genome` script. Solution would cost <30 sec, so its not too bad.

**Comment by Maarten-vd-Sande** [comment]
I think the cleanest way is to have it as output of both, and set a ruleorder (maybe not even necessary). Not entirely sure if that's possible though :thinking: 

I don't like keeping the warning, because it can put people on the wrong foot. Removing the file is also ok, but indeed a bit mehh. But I prefer this over doing nothing
