### ISSUE TITLE
BUG: '-j' is not in list

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#711]
**Describe the bug**
running a workflow with a `profile` causes an error in this line:
`cores_index = cli_call.index("--cores" if "--cores" in cli_call else "-j")`

**Screenshots**
![image](https://user-images.githubusercontent.com/48289046/120509459-cfac8e80-c3c8-11eb-8e5c-a893d3a957a4.png)

**Comment by Maarten-vd-Sande** [comment]
Woops accidentally pushed fix directly to develop: https://github.com/vanheeringen-lab/seq2science/commit/c3cf1d368975e1f396e27d39fcef6f6ce5df494b
