### ISSUE TITLE
FR: auto-formatting

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#712]
**what**
Would we like to implement a pre-commit hook/test step which performs formatting?

**how**
Snakemake's own version of `black`,  `snakefmt`, is working in most cases.
By running it on 1 file at a time, cryptic errors are slightly more clear.

example with a line-length of 122 (arbitrary, but we've used it because of pycharm)
```
mamba install snakefmt

for file in seq2science/rules/*; do 
  snakefmt -l 122 $file
done
```

**Comment by Maarten-vd-Sande** [comment]
I think a non-optional test could be nice. Not sure how buggy/time consuming it would be to make what we have now work with snakefmt

**Comment by siebrenf** [comment]
Snakefmt improves readability a bit, but still needs supervision. Lets keep this open for now, and I'll make a PR manually this time.
