### ISSUE TITLE
FR: Make it easy to work with your "own" assembly

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#758]
**Is your feature request related to a problem? Please describe.**
It is now difficult / nearly impossible to load your own. Should we add a command, `s2s load genome` or whatever? We should experiment a bit with this

**Comment by Maarten-vd-Sande** [comment]
I think currently a big issue is that the timestamps of some of the files should be in a certain order, otherwise snakemake gets really unhappy and tries to redownload stuff

**Comment by siebrenf** [comment]
We'll need to check every step that uses a genome (related) file and make sure they are `ancient()`...
I thought I fixed that already :/

**Comment by Maarten-vd-Sande** [comment]
maybe all we need is clear documentation :shrug:

**Comment by quan-xu** [comment]
Hi Maarten and Siebren, do you have a good way to solve this "own" assembly problem now? 😛

**Comment by siebrenf** [comment]
Hey Quan! It's not super easy, so I'll post the code with explanation.

using `genomepy 0.11.1`, you can install your "own" assembly with
```
genomepy  install \
--provider local \
/path/to/genome.fa \
--genomes_dir /path/to/genomes_dir \
--localname new_name_for_this_genome \
--annotation \
--Local-path-to-annotation /path/to/annotation.gtf \
--skip_filter
```
check `genomepy install --help` for more details.

Next, in the seq2science config.yaml, set your `genome_dir` to the same `/path/to/genomes_dir`.
Finally, run seq2science with the flag `--skip-rerun`.

**Comment by quan-xu** [comment]
Hi Sibren, thank you very much! It works!

**Comment by Maarten-vd-Sande** [comment]
Is the skip-rerun even necessary? I think all you need to work with your own genome is just a fasta file in `{genomes_dir}/{assembly}/{assembly}.fa` and for rna-seq also `{genomes_dir}/{assembly}/{assembly}.annotation.gtf`.

**Comment by siebrenf** [comment]
Maybe I like to tweak my settings too often, but I usually need `--skip-rerun` to prevent regenerating my genome, annotation and indexes. 

With a custom genome, an accidental rerun would delete the files, then complain genomepy can't download the files 🙈

**Comment by siebrenf** [comment]
for RNA-seq you will also need `{genomes_dir}/{assembly}/{assembly}.annotation.bed`
