### ISSUE TITLE
BUG: InputFunctionException in line 669 of trackhub

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#759]
**Describe the bug**
When using technical replicates with rna-seq the strandedness inference seems bugged. It goes wrong on this line:
https://github.com/vanheeringen-lab/seq2science/blob/master/seq2science/rules/trackhub.smk#L299

```
InputFunctionException in line 669 of /home/sande/Desktop/seq2science/seq2science/rules/trackhub.smk:
KeyError: 0
Wildcards:
```

**Comment by siebrenf** [comment]
Works with a fresh install (of the develop branch).
