### ISSUE TITLE
BUG: Chip-seq workflow is not running

### ISSUE THREAD

**Issue by XimenezJP** [vanheeringen-lab/seq2science#766]
Hi,

I have been trying to run the chip-seq workflow of seq2science. I am having trouble with mark_duplicates.

```r
seq2science --version
seq2science: v0.5.6
```

**To Reproduce**
Please include your **config.yaml**, your **samples.tsv**, and the complete/relevant **output**.

**config.yaml**
```r
# tab-separated file of the samples
samples: samples.tsv

# pipeline file locations
result_dir: ./results  # where to store results
genome_dir: ./genomes  # where to look for or download the genomes
fastq_dir: /data1/home/joao/chip_seq/  # where to look for or download the fastqs


# contact info for multiqc report and trackhub
email: yourmail@here.com

# produce a UCSC trackhub?
create_trackhub: true

# how to handle replicates
biological_replicates: fisher  # change to "keep" to not combine them
technical_replicates: merge    # change to "keep" to not combine them

# which trimmer to use
trimmer: fastp

# which aligner to use
aligner: bwa-mem2

# filtering after alignment
remove_blacklist: true
min_mapping_quality: 30
only_primary_align: true
remove_dups: true

# peak caller
peak_caller:
  macs2:
      --buffer-size 10000
#  genrich:
#      -y -q 0.05

## differential peak analysis
#contrasts:
#  - 'descriptive_name_all_HEL'
```

**samples.tsv**
```r
# for help with filling out the samples.tsv:
# https://vanheeringen-lab.github.io/seq2science/content/workflows/chip_seq.html#filling-out-the-samples-tsv
# also make sure that you use tab as a delimiter
sample   assembly        descriptive_name
U343HOXB2       GRCh38.p13      U343HOXB2
```

**Error Messages**

- log file
[GRCh38.p13-U343HOXB2.log](https://github.com/vanheeringen-lab/seq2science/files/7425613/GRCh38.p13-U343HOXB2.log)

- terminal output
[seq2science.2021-10-26T220457.241748.log](https://github.com/vanheeringen-lab/seq2science/files/7425649/seq2science.2021-10-26T220457.241748.log)

The log file said that there is **no space left on device** but I still have space in my server.

I hope you could help me!

**Comment by Maarten-vd-Sande** [comment]
@XimenezJP how did it go?

**Comment by XimenezJP** [comment]
Hi Maarten,

Sorry for not getting back to you sooner! The server was busy!

I have great news! 

Chip-seq is running! I have added `TMP_DIR` in my `config.yaml`. 

Thank you!

Joao

**Comment by Maarten-vd-Sande** [comment]
Awesome! I'm closing this issue then :smile:
