### ISSUE TITLE
BUG: Broken assembly stats for custom reference (kb kite)

### ISSUE THREAD

**Issue by tilschaef** [vanheeringen-lab/seq2science#774]
**Describe the bug**
When running the kb with `--workflow kite` seq2science exits with the following key error:

```
InputFunctionException in line 618 of /vol/mbconda/tschaefers/envs/s2s/lib/python3.8/site-packages/seq2science/rules/qc.smk:
KeyError: 'fb'
Wildcards:
assembly=fb
```

**Expected behavior**
kb uses a custom set of reference transcripts, Antibody barcodes, to build the index which cannot be retrieved via Genomepy. I suspected it goes wrong in `assembly_stats_input`. The genome path for kite should be `{genome_dir}/{assembly}/index/kallistobus/kite/{assembly}.fa and there is no ".fai" index.

**Comment by Maarten-vd-Sande** [comment]
Hah awesome! First bug reported even before it's released :smile: 

I'll take a look in a bit!
