### ISSUE TITLE
BUG: Seq2science is not creating conda environments (scRNA workflow)

### ISSUE THREAD

**Issue by tilschaef** [vanheeringen-lab/seq2science#784]
**Describe the bug**
This concerns the development branch. I have been testing the scRNA workflow on a couple of datasets and it appears that the workflow gets stuck on creating the conda environment for Multiqc. Can anyone reproduce that behavior for different workflows?  Dryruns work as expected. 

Could it be related to the newest Snakemake version?

`Building DAG of jobs...
Done. Now starting the real run.
Building DAG of jobs...
Creating conda environment /vol/mbconda/tschaefers/envs/s2s/lib/python3.8/site-packages/seq2science/rules/../envs/multiqc.yaml...
Downloading and installing remote packages.
`

**Comment by siebrenf** [comment]
yes. downgrade mamba to 0.17

**Comment by siebrenf** [comment]
I've updated the `environment.yaml` in the develop branch

**Comment by tilschaef** [comment]
Thanks, that did the trick!

**Comment by Maarten-vd-Sande** [comment]
Do we have any clue why this happens?

**Comment by Maarten-vd-Sande** [comment]
Don't we have tests that install multiqc? Why do those work?

**Comment by siebrenf** [comment]
Maybe Jenkins is not reinstalling the default env? I experience this too with another env, but thought I'd probably just broke something locally. [Turns out we're not the only ones](https://github.com/snakemake/snakemake/issues/1287).
