### ISSUE TITLE
FR: R `samples` read from samples.to_string in params instead of parse in R

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#790]
**Is your feature request related to a problem? Please describe.**
Might be a more sustainable way of doing these things

I guess in a sense related to #537, and should fix that

Related : #788

**Comment by siebrenf** [comment]
`deseq2science` currently needs to parse the samples.tsv file within R, so we'll still need this function anyway. Can let this go stale...

We could refactor deseq2science, and make it a snakemake workflow as well, but this has no priority, so I probably wont.
