### ISSUE TITLE
FR: scRNA quality score per plate well

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#799]
from meeting

**Comment by Maarten-vd-Sande** [comment]
I heard @Rebecza has something for this? Making a small custom script that does this should be pretty straight forward as well. 

I think the difficulty lays with the ordering of the cells on the plate, not the actual visualization. Is there a straight forward way to infer this? Do cells on certain locations always have the same barcodes/umis we could target? How would we infer that from the count table...?

**Comment by tilschaef** [comment]
There is indeed already a solution for this in @Rebecza  scRNA workflow. Basically, you now each spot of the 384 plate in advance and it visualizes the total UMI count per cell.  It is just a matter of adding the script after the object merging.
