### ISSUE TITLE
BUG: inconsequential CLI changes prompt reruns

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#823]
**Describe the bug**
Changing the number of cores should not prompt reruns.

I'll add other options to the list if I find them.

**Comment by Maarten-vd-Sande** [comment]
Ah good catch! Does it re-run everything or a small-ish selection/branch only (e.g. qc report)? I can imagine params like this causes the qc stuff to be re-run. Seems like we need a config parsing function for this :see_no_evil: 

https://github.com/vanheeringen-lab/seq2science/blob/master/seq2science/rules/qc.smk#L502

I would expect both snakemakeoptions to cause the same behavior

**Comment by siebrenf** [comment]
these rules use threads in their params:

- bam2cram
- fastp_SE
- fastp_PE
- samtools_presort
- samtools_sort

these rules seem to get params changes listed:

- multiqc_explain
- multiqc_header_info
- multiqc_samplesconfig

Finally, the fastp rules seem to get marked all the time, even when threads are removed from the params. Could this be related to the `temp()`?

**Comment by Maarten-vd-Sande** [comment]
I think you've solved this right?
