### ISSUE TITLE
Q: should we clean up all the installed environments after a succesful run?

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [vanheeringen-lab/seq2science#843]
**Question**

Seq2science installs a couple GBs of conda envs after a run. Should we uninstall those by default on a succesful run? Could be a flag that can be turned on/off?

@siebrenf and @tilschaef what do you think?

**Comment by siebrenf** [comment]
A config flag to (not) remove the conda environments on a successful run sounds like it could be useful. It should also be clear enough for anyone who takes the time to read the config file, so it's not too much babysitting.

**Comment by Maarten-vd-Sande** [comment]
For future reference: I noticed that the newer snakemake has options such as 'conda_cleanup_pkgs' and 'conda_cleanup_envs'

https://snakemake-api.readthedocs.io/en/latest/api_reference/snakemake.html
