### ISSUE TITLE
BUG: softmask_track_1 gets stuck

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/seq2science#886]
**Describe the bug**
Jenkins sometimes gets stuck on rule softmask_track_1 [rule](https://github.com/vanheeringen-lab/seq2science/blob/5c13d49417ccd76cde90aace2279effdf4928726/seq2science/rules/trackhub.smk#L128). 

http://ocimum.science.ru.nl/jenkins/blue/organizations/jenkins/seq2science/detail/PR-884/1/pipeline/
http://ocimum.science.ru.nl/jenkins/blue/organizations/jenkins/seq2science/detail/develop/250/pipeline/
http://ocimum.science.ru.nl/jenkins/blue/organizations/jenkins/seq2science/detail/develop/148/pipeline/97

**possible solutions?**
- end the rule with `pool.join()`
- add a timeout + retry
- switch from imap to async

**Comment by Maarten-vd-Sande** [comment]
I think this was solved right?
