### ISSUE TITLE
BUG: barcode concatination scATAC

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/seq2science#889]
**Describe the bug**
When running s2s scATAC 0.9.2, the scATAC workflow doesnt correctly register the single cell barcodes. The resulting snap object thinks all reads are all from the same cell. 

**To Reproduce**
run scATAC, within the resulting sample-genome.snap.qc file:

Total number of unique barcodes:             1
TN - Total number of fragments:              12673129
UM - Total number of uniquely mapped:        12673129
SE - Total number of single ends:            68096
SA - Total number of secondary alignments:   0
PE - Total number of paired ends:            12605033
PP - Total number of proper paired:          12591166
PL - Total number of proper frag len:        12591166
US - Total number of usable fragments:       12591166
UQ - Total number of unique fragments:       12591014
CM - Total number of chrM fragments:         0

**Expected behavior**
Total number of unique barcodes should be more than 1. This was not a problem in v0.4.2 (wich is the last time i ran it completely)

Total number of unique barcodes:             203
TN - Total number of fragments:              23291720
UM - Total number of uniquely mapped:        23291720
SE - Total number of single ends:            283049
SA - Total number of secondary alignments:   0
PE - Total number of paired ends:            23008671
PP - Total number of proper paired:          22672582
PL - Total number of proper frag len:        22672582
US - Total number of usable fragments:       22672582
UQ - Total number of unique fragments:       22671984
CM - Total number of chrM fragments:         0

Up until then as far as I can find in the changelog the only alterations which might play a role:

[v0.5.1]  "scATAC can properly use SE fastqs"
[v0.5.3]"biological_replicate" and "technical_replicate" renamed to *"_replicates" (matches between samples.tsv & config.yaml)
[v0.93] "fixed custom assembly extensions (e.g. ERCC spike-ins) for scATAC-seq and scRNA-seq"

Potentially the replication renaming might cause some problems? Since in the scATAC workflow all replica's are different cells wich are concatinated in the snap-object. But perhaps since 0.4.2 this is shifted to a different step?

I'm currently re-running my data on 0.4.2 to see if this indeed fixes the problem for my own data. I'll send a message here once I'm sure, but my gut feeling is something with the SE fastq or the new replica names might have changed things?

Gr Jos

**Comment by siebrenf** [comment]
The bug seems to happen in snaptools. The input for the snaptools rules wasn't changed [since the initial commit](https://github.com/vanheeringen-lab/seq2science/blame/db4479e1239e8f878e158c50407e4c6bb27b43e5/rules/scATAC.smk) so I'm stumped :o

Perhaps it's related to these logged errors? This is the `snaptools snap-pre` log (using only 1 bam):
```
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
[E::idx_find_and_load] Could not retrieve index file for '/home/siebrenf/git/seq2science/results/final_bam/hg38-H1ESC.sambamba-queryname.bam'
```

Now here is the fun part: Neither samtools nor sambamba can index queryname sorted files. [And We're not the only ones getting it.](https://github.com/r3fang/SnapTools/issues/40)

**Comment by JGASmits** [comment]
I think i am narrowing down the problem, it is related to the presence/absence of the barcode ID in the BAM file header (not related to the index error). Will look further on monday.

**Comment by JGASmits** [comment]
Alright, I'm pretty sure I found where the bug arises, already in 'merge_replicates':

`
    rule merge_replicates:
        """
        Merge replicates (fastqs) simply by concatenating the files. We also change the name of the read headers to 
        contain the name of the original replicate.
        Must happen after trimming due to trim-galore's automatic adapter trimming method 
        If a replicate has only 1 sample in it, simply move the file.
        """
        input:
            get_merge_replicates,
        output:
            temp(sorted(expand("{trimmed_dir}/{{replicate}}{{fqext}}_trimmed.{fqsuffix}.gz", **config))),
        wildcard_constraints:
            replicate="|".join(true_treps) if len(true_treps) else "$a",
            fqext=f"_{config['fqext1']}|_{config['fqext2']}|",  # nothing (SE), or fqext with an underscore (PE)
        params:
            reps=lambda wildcards, input: input,  # help resolve changes in input files
        log:
            expand("{log_dir}/merge_replicates/{{replicate}}{{fqext}}.log", **config),
        benchmark:
            expand("{benchmark_dir}/merge_replicates/{{replicate}}{{fqext}}.benchmark.txt", **config)[0]
        run:
            for rep in input:
                rep_name = re.findall("/([^/_]+)_", rep)[-1]

                shell(
                    """zcat {rep} | awk '{{if (NR%4==1) {{gsub(/^@/, "@{rep_name}:"); print}} else {{print}}}}' | gzip >> {output}"""
                )`


Where it goes wrong I think is:
"We also change the name of the read headers to 
        contain the name of the original replicate." 

This does not properly happen with my fastq file naming. Reads from different fastq files ended up with the same header name in the BAM file. This causes the sc-pipeline to assume they are all from the same cell, which caused the problems downstream.

I think if igured it out, merge replica's ( re.findall("/([^/_]+)_", rep)[-1]) takes everything from: downstream of '/" and upstream of the first "_" right?

This causes my fastq files wich are:
293_N705_S18_S9_R1_001.fastq.gz
293_N705_S19_S10_R1_001.fastq.gz

to all be renamed to: "293" instead of their whole name wich included the barcode.

Ina n ideal word I guess it would be better for the command to take everything up untill the {fqext1} as a rep_name.
However I think for now its easier for me to just rename my fastq files into something else.
If it works with renamed fastq files, ill make a note in the scATAC documentation and close the topic.

Gr Jos

**Comment by JGASmits** [comment]
It was indeed the fastq merging that is the problem, easiest fix was to rename the fastq files to just not have any "_" in their names.

**Comment by Maarten-vd-Sande** [comment]
This is maybe easily fixable with a better regex?
