### ISSUE TITLE
BUG: Bigwig files not transferred to trackhub folder

### ISSUE THREAD

**Issue by jroubroeks** [vanheeringen-lab/seq2science#902]
After a succesful rna-seq workflow run, a trackhub is generated, but not all bigwig files are located in the `/results/trackhub/hg38/` folder. I have encountered this issue after running four different analyses. As far as I can see, no errors are raised in the log files, and all bigwig files are present in the `/results/bigwigs/` folder. This issue seems to only apply to `reverse.bigwig` files, but not _all_ `reverse.bigwig` files are missing.

Running `seq2science run rna-seq` a second time seems to fix the issue.

**Comment by Maarten-vd-Sande** [comment]
Assuming this is solved now? Feel free to re-open
