### ISSUE TITLE
BUG: [The new version of `matplotlib` will lead to some bugs in some rules.]

### ISSUE THREAD

**Issue by bioqxu** [vanheeringen-lab/seq2science#907]
**Describe the bug**
In the `atac-seq` run, I saw that `upset_plot_peaks` and `plotHeatmap_peak` had errors, which can be solved by downgrading the `matplotlib` from `3.6` to `v3.5`.

**Comment by Maarten-vd-Sande** [comment]
Thanks for reporting @bioqxu :smile:/ We are aware and should be fixed in `develop`. I'll make a new release today, somehow got passed me

**Comment by Maarten-vd-Sande** [comment]
Oh the `plotHeatmap_peak` one is new to me! I'll add it as well

**Comment by bioqxu** [comment]
HAHA😁! Thanks!
